// コラム（column.html / column-<id>.html）の画面文言。
// 記事本文の英訳は columns-en.js（COLUMN_EN）。日本語の出典は js/data.js の
// COLUMN_ARTICLES。HTML は日本語のまま出力し（SEO）、英語は読み込み後に差し替える。
import { registerDict, t, tf } from '../i18n.js';

registerDict({
  // -- column.html (list) --
  'column.list.title': { ja: 'コラム | PhotoMatch', en: 'Column | PhotoMatch' },
  'column.list.metaDesc': {
    ja: '「マッチしない原因」「写真の撮り方」「服装」——マッチングアプリで結果を出すためのヒントを、名古屋の撮影現場からお届けします。',
    en: 'Why you are not getting matches, how to take better photos, what to wear: tips for getting results on dating apps, straight from our Nagoya shoots.',
  },
  'column.list.heading': { ja: '写真とマッチングアプリのコラム', en: 'Photos & Dating Apps: Our Column' },
  'column.list.lead': {
    ja: '「マッチしない原因」「写真の撮り方」「服装」——アプリで結果を出すためのヒントを、名古屋の撮影現場からお届けします。',
    en: 'Why you are not getting matches, how to take better photos, what to wear: tips for getting results on dating apps, straight from our Nagoya shoots.',
  },
  'column.backToTop': { ja: '← トップに戻る', en: '← Back to Top' },

  // -- shared by the list and the article pages --
  'column.readMin': { ja: '読了 約{min}分', en: 'About {min} min read' },
  'column.tag.local': { ja: '名古屋ローカル', en: 'Nagoya Local' },
  'column.tag.howto': { ja: 'ノウハウ', en: 'How-To' },
  'column.tag.solve': { ja: 'お悩み解決', en: 'Troubleshooting' },
  'column.tag.byApp': { ja: 'アプリ別', en: 'By App' },
  'column.tag.price': { ja: '料金', en: 'Pricing' },

  // -- column-<id>.html (articles; generated by scripts/build-articles.mjs) --
  'column.backToList': { ja: '← コラム一覧に戻る', en: '← Back to All Columns' },
  'column.related': { ja: 'ほかのコラム', en: 'More Columns' },
  'column.cta.title': { ja: 'その一枚、プロと45分で。', en: 'That one great photo, with a pro in 45 minutes.' },
  'column.cta.body': {
    ja: '名古屋・岐阜エリアの審査済みカメラマンが、アプリ映えする自然な1枚を撮影します。',
    en: 'A vetted photographer in the Nagoya and Gifu area will shoot a natural photo that looks great on dating apps.',
  },
  'column.cta.button': { ja: '撮影を予約する', en: 'Book a Session' },
});

// Japanese tag (as stored in COLUMN_ARTICLES.tag) -> dictionary key.
const TAG_KEYS = {
  '名古屋ローカル': 'column.tag.local',
  'ノウハウ': 'column.tag.howto',
  'お悩み解決': 'column.tag.solve',
  'アプリ別': 'column.tag.byApp',
  '料金': 'column.tag.price',
};

// Falls back to the Japanese tag for one that has no entry yet.
export const tagText = (ja) => (TAG_KEYS[ja] ? t(TAG_KEYS[ja]) : ja);

export const readMinText = (min) => tf('column.readMin', { min });
